// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcITl8myjvabrnwAcWlA805J3mLkK1gE',
    appId: '1:922424141325:web:589736d644029c6ffd9744',
    messagingSenderId: '922424141325',
    projectId: 'alonsodev-59063',
    authDomain: 'alonsodev-59063.firebaseapp.com',
    storageBucket: 'alonsodev-59063.appspot.com',
    measurementId: 'G-6K79YXWRCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDttZ9BtpHMhSmSsUSKClhs-zSnU-7Olw',
    appId: '1:922424141325:android:9126ffb8a7c82be5fd9744',
    messagingSenderId: '922424141325',
    projectId: 'alonsodev-59063',
    storageBucket: 'alonsodev-59063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UPGtJhgHSB6e0F4UA0LbRI7pDug6kGY',
    appId: '1:922424141325:ios:37af6cf7b2658b3dfd9744',
    messagingSenderId: '922424141325',
    projectId: 'alonsodev-59063',
    storageBucket: 'alonsodev-59063.appspot.com',
    androidClientId: '922424141325-2hqrq3aqbavsaqsl2n32tmkrrcqama02.apps.googleusercontent.com',
    iosClientId: '922424141325-nc8ib8konc2r901akmk723g96pje14te.apps.googleusercontent.com',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0UPGtJhgHSB6e0F4UA0LbRI7pDug6kGY',
    appId: '1:922424141325:ios:37af6cf7b2658b3dfd9744',
    messagingSenderId: '922424141325',
    projectId: 'alonsodev-59063',
    storageBucket: 'alonsodev-59063.appspot.com',
    androidClientId: '922424141325-2hqrq3aqbavsaqsl2n32tmkrrcqama02.apps.googleusercontent.com',
    iosClientId: '922424141325-nc8ib8konc2r901akmk723g96pje14te.apps.googleusercontent.com',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhcITl8myjvabrnwAcWlA805J3mLkK1gE',
    appId: '1:922424141325:web:1ec6be45daa52c74fd9744',
    messagingSenderId: '922424141325',
    projectId: 'alonsodev-59063',
    authDomain: 'alonsodev-59063.firebaseapp.com',
    storageBucket: 'alonsodev-59063.appspot.com',
    measurementId: 'G-28JRRFF6V4',
  );
}
